# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0KA3MeqEjQW7NJJqupKkQfUyuvUTR1D
"""

list=[2,2.5,"Hari"]
print(list)

d=(2,4,12,"Hari")
print(d)

a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

c=['a','b','c','d','e','f']
print(c[1:3])


def predict_marks(hours, age):

    if hours < 1:
        if age < 16:
            return "Below average" 
        else:
            return "Predicted marks: Poor"
    elif hours >= 1 and hours < 4:
        if age < 16:
            return "Predicted marks: Average"
        else:
            return "Predicted marks: Good"
    else:
        if age < 16:
          return "Predicted marks: Above average"
        else:
            return "Predicted marks: Excellent"
print(predict_marks(3,14)







